projectTitle = "Reef"
modId = "reef"
modVersion = "0.3.0+1.21.10-alpha.3"
group = "org.teamvoided"
githubRepo = "Teamvoided/Reef"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore","DuskAutumnStorm" ]
majorMinecraftVersion = ">=1.21.10"
minecraftVersion = "1.21.10"
fabricLoaderVersion = "0.17.3"
fabricApiVersion = "0.136.0+1.21.10"
fabricLangKotlinVersion = "1.13.2+kotlin.2.1.20"
license = "MIT"
modules = [ ]
modDescription = "Library that extends vanilla worldgen by providing alternatives to unmodifiable features"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ "library" ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.10"