org.gradle.jvmargs=-Xmx4G


mod_version = 0.1.1
maven_group = org.teamvoided
modid = reef
mod_name = Reef
description = Library that extends vanilla worldgen by providing alternatives to unmodifiable features

# Modrinth and CurseForge Ids for this project
modrinth_id = AqJVwCCS
curse_id = 10078450

archives_base_name = reef

kotlin.code.style=official
